### ISSUE TITLE
Italian traslation

### ISSUE THREAD

**Issue by fabiograz** [icodebetter/icodebetter#10]
Hi,
I'm evaluating this framework to use as development platform. But, I found that there isn't Italian translation of it. 
How can I translate the framework to add Italian translation? Can I help you contributing to that?

Send me how-to. 
Thanks,
Fabio.

**Comment by hugsyy** [comment]
@fabiograz Hello, do you mean whole platform in Italian or documentation?

**Comment by fabiograz** [comment]
I'm interested in platform. It seems a valid lowcode platform and I want contribute it (not to the code develop). The documentation also but, it seems lack in english too. For exemple some arguments could be:
- how to deploy the applications
- how to upgrade the framework
- how to access data from DB client
- the DB structure
and so on.

Please, say me how I may help in translate to italian.

Fabio

**Comment by hugsyy** [comment]
@fabiograz We appreciate your willingness to help and thank you for your feedback.

- Deployment: In enterprise edition we have integrated DevOps with Kubernetes and Docker. Soon, we will make Docker Deployment integration available in community edition. And update documentation with Docker tutorial as well.
- Upgrading framework: We will add this info to docs today.
- DB client access: We will add tutorial for it today.
- DB structure: We will add this soon.
- Translation: We need to set up our docs for pull requests/contributions. As soon as we do that we will let you know and you can start contributing to docs. We think that docs should be translated first and then the platform. While you are contributing to the docs we will be preparing How-To for the platform. And once that's ready you can contribute to the platform translation as well. 

If you have any other feedback or request, we would love to hear them.

**Comment by fabiograz** [comment]
@hugsyy I appreciate your speed to integrate documentations.
I'm waiting for other documentations and to contributing.

Thanks,
Fabio.
