### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by fabiograz** [icodebetter/icodebetter#11]
Hi,
Is it possible to develop a multi tenant application with this platform?
I need develop a application where:
- many companies access to the same application but, see only datas of theirs
- for any company, users may have different role and so they must access only to some forms or some fields are set not visible or not editable by them.

If it is possible, where can I found the concerning documentation?

Thanks,
Fabio.

**Comment by hugsyy** [comment]
@fabiograz Hello, yes it is possible. We will write tutorial for that. In tutorial, we will cover how to add tenant table to framework, add tenant to authentication and session query,etc.

**Comment by fabiograz** [comment]
Ok,
I'm waiting.

Thanks.
