### ISSUE TITLE
Error in tutorial's page "Getting Started"

### ISSUE THREAD

**Issue by fabiograz** [icodebetter/icodebetter#12]
HI.

**What you did**:
I follow the tutorial's page "Getting started". 

**What happened**:
In this text:
"Under Core Development Tools panel there is application menu. Here, you can see templates that you created. The red button is used to reload framework cache. And test is a template's name.":
- red button doesn't exist in IcodeBetter
- there isn't any template named "test" in the image.

![immagine](https://user-images.githubusercontent.com/11799153/58606977-e7af1c00-829d-11e9-99f9-9fc6374319b9.png)

**Problem description**:

Text doesn't fit image or UI of ICodeBetter. 
Can you correct this page?

Thanks,
Fabio

**Comment by hugsyy** [comment]
@fabiograz Thank you for your feedback, it is fixed now.

**Comment by fabiograz** [comment]
Thanks!
