### ISSUE TITLE
 is your backup file up-to-date

### ISSUE THREAD

**Issue by fatihcelen** [icodebetter/icodebetter#16]
**What you did**: First Debug iCodebetter system.

**What happened**: Getting the following error. is your backup file up-to-date?

**Problem description**:
{"success":false, "errorType":"framework","error":"HATA: \"iwb.w5_external_db\" nesnesi mevcut değil\n Position: 397", "objectType":"DataBase.Exception", "stack":"iwb.exception.IWBException: Custom Query2List: HATA: geçerli transaction durduruldu, transaction blokunun sonuna kadar komutlar yok sayılacak\n\tat iwb.dao.rdbms_impl.BaseDAO.executeSQLQuery(BaseDAO.java:249)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadFrameworkCaches(MetadataLoaderDAO.java:1458)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$FastClassBySpringCGLIB$$1e052681.invoke()\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n\tat org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$EnhancerBySpringCGLIB$$89d1b441.reloadFrameworkCaches()\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$FastClassBySpringCGLIB$$1e052681.invoke()\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$EnhancerBySpringCGLIB$$c146c1d4.reloadFrameworkCaches()\n\tat iwb.service.FrameworkService.saveCredentials(FrameworkService.java:1969)\n\tat iwb.service.FrameworkService$$FastClassBySpringCGLIB$$f1b24cca.invoke()\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\n\tat org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)\n\tat iwb.service.FrameworkService$$EnhancerBySpringCGLIB$$5bc9b6d7.saveCredentials()\n\tat iwb.controller.AuthController.handle(AuthController.java:133)\n\tat iwb.controller.AuthController.getCallback(AuthController.java:76)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:635)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:742)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat iwb.filter.AppFilter.doFilter(AppFilter.java:54)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Thread.java:835)\nCaused by: org.hibernate.exception.GenericJDBCException: error executing work\n\tat org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)\n\tat org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:337)\n\tat org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2153)\n\tat org.hibernate.internal.SessionImpl.doReturningWork(SessionImpl.java:2149)\n\tat iwb.dao.rdbms_impl.BaseDAO.executeSQLQuery(BaseDAO.java:210)\n\t... 83 more\nCaused by: org.postgresql.util.PSQLException: HATA: geçerli transaction durduruldu, transaction blokunun sonuna kadar komutlar yok sayılacak\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)\n\tat jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)\n\tat com.sun.proxy.$Proxy82.executeQuery(Unknown Source)\n\tat iwb.dao.rdbms_impl.BaseDAO$1.execute(BaseDAO.java:226)\n\tat iwb.dao.rdbms_impl.BaseDAO$1.execute(BaseDAO.java:1)\n\tat org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55)\n\tat org.hibernate.internal.SessionImpl$4.accept(SessionImpl.java:2146)\n\tat org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:332)\n\t... 86 more\nCaused by: org.postgresql.util.PSQLException: HATA: \"iwb.w5_external_db\" nesnesi mevcut değil\n Position: 397\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)\n\tat jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)\n\tat com.sun.proxy.$Proxy82.executeQuery(Unknown Source)\n\tat org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)\n\tat org.hibernate.loader.Loader.getResultSet(Loader.java:2117)\n\tat org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1900)\n\tat org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)\n\tat org.hibernate.loader.Loader.doQuery(Loader.java:919)\n\tat org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)\n\tat org.hibernate.loader.Loader.doList(Loader.java:2617)\n\tat org.hibernate.loader.Loader.doList(Loader.java:2600)\n\tat org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)\n\tat org.hibernate.loader.Loader.list(Loader.java:2424)\n\tat org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)\n\tat org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)\n\tat org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)\n\tat org.hibernate.internal.SessionImpl.list(SessionImpl.java:1326)\n\tat org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)\n\tat iwb.dao.rdbms_impl.BaseDAO.find(BaseDAO.java:63)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadExternalDbsCache(MetadataLoaderDAO.java:933)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadProjectCaches(MetadataLoaderDAO.java:1594)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadFrameworkCaches(MetadataLoaderDAO.java:1455)\n\t... 82 more\n", "sql":"select x.related_project_uuid, string_agg(x.user_id::text,',') from iwb.w5_user_related_project x group by x.related_project_uuid", "icodebetter":[{"errorType":"request","objectType":"Web.Request","error":"/auth/callback"},{"errorType":"sql","error":"Custom Query2List: HATA: geçerli transaction durduruldu, transaction blokunun sonuna kadar komutlar yok sayılacak","sql":"select x.related_project_uuid, string_agg(x.user_id::text,',') from iwb.w5_user_related_project x group by x.related_project_uuid","objectType":"Custom.Query.List","objectId":0},{"errorType":"framework","error":"HATA: \"iwb.w5_external_db\" nesnesi mevcut değil\n Position: 397","objectType":"DataBase.Exception","objectId":0}]}

**Comment by hugsyy** [comment]
Hi @fatihcelen, are you setting up the system using docker? If so, please read https://github.com/icodebetter/icodebetter/issues/9#issuecomment-496092964 or https://docs.icodebetter.com/local-setup

**Comment by azatTemirbek** [comment]
I guess there is missing table iwb.w5_external_db maybe you will try to create on your local db manually
