### ISSUE TITLE
icodebetter dosya yükleme

### ISSUE THREAD

**Issue by selimsahindemir** [icodebetter/icodebetter#17]
Merhaba;

yapmış olduğumuz forma dosya eklemek istiyoruz fakat dosya yükleme kısmı çalışmıyor. Dosya yüklemek istediğimizde Uncaught ReferenceError: DetectFlashVer is not defined böyle bir hata oluşuyor console içerisinde yazıyor.

Eklemiş olduğum tabloda Dosya yükle işaretli dediğimizde otomatik dosya yükleme çıkıyor. Fakat dosya yükle dediğimde hiç bir tepki vermiyor.

Şimdiden ilginiz için teşekkürler.

**Comment by hugsyy** [comment]
@selimsahindemir Merhaba, nerede calisiyorsunuz? Localdemi icb.world demi? Hangi template kullaniyor sunuz (React, Extjs..)? Eger icb.world de calisiyorsaniz beni ekleyin projeye. Yukarida sagda insanlar ikonuna tiklayarak sonra arti butonuna tiklayip 'ulugbek' yazin.
![scrn_team](https://user-images.githubusercontent.com/16086407/64845320-8889d300-d612-11e9-9a96-34830d770d80.png)

**Comment by selimsahindemir** [comment]
merhaba ulugbek. Ben lokalde çalışıyorum fakat icb.world hesap var seni ekledim. template olarak Extjs kullanıyorum.
