### ISSUE TITLE
Eksikler

### ISSUE THREAD

**Issue by selimsahindemir** [icodebetter/icodebetter#18]
Merhaba Ulugbek;

Son güncellemeden sonra gördüğüm eksikler

1. Grid başlığındaki yorum iconu gitti
2. Raporladaki isimler gitti (pdf,excel vs.)
3. Grafik, datalist ve pivot gitti
4. Otomatik combodaki yazı lokal yazıya döndü (autocomplete_placeholder)
5. vcs bağlantısı gitti

**Comment by hugsyy** [comment]
Merhaba,
VCS baglantisi gitmemesi lazim source kodda yeni vcs url var. Baglanmiyorsa eclipse de debug configuration'da `vcs_server=http://18.189.84.73/app/` parametresi ile deneyebilir siniz. Diger konular hakkinda bilgim yok sormam lazim...

**Comment by selimsahindemir** [comment]
Merhaba;

Son güncellemeden sonra gördüğüm eksikler

    1. Gridlerde bulunan yorum alanının iconu gitti
    2. Grafik, datalist ve pivot gitti
