### ISSUE TITLE
grape.js or frontend builder

### ISSUE THREAD

**Issue by excitedbox** [icodebetter/icodebetter#22]
Love the App builder. I think it would be really cool if you added grape.js so you can build frontend layouts and insert data that is stored in tables. Not only could you display list views but you could also setup a table as a content storage and use the individual rows to fill the page content. That way not only could you build a business app but an entire website.

**Comment by hugsyy** [comment]
@excitedbox Thank you for your suggestions, we will consider grape.js when we expand the platform's features in the future.
