### ISSUE TITLE
Problem in entering integer value in input field of the form as UI component

### ISSUE THREAD

**Issue by rajotron** [icodebetter/icodebetter#5]
**What you did**: I have tried using integer, double as ui component in the input field but didn't got the result.

**What happened**:  Either it is giving object error while entering or didn't allowed to enter number having length greater than 6. I want to enter a phone number having length 10.

**Problem description**:

**Comment by e178551** [comment]
A simple solution would be to use String input and give props {maxLenght:10} on props.

**Comment by rajatsehgal2010** [comment]
I have tried that but the alert message comes with message "Object [Object]"
