### ISSUE TITLE
Tables does not Exist

### ISSUE THREAD

**Issue by fabiograz** [icodebetter/icodebetter#9]
I'm trying to local install Icodebetter with docker's containers as described in https://docs.icodebetter.com/local-setup (I've changed db with db2 as  in https://github.com/icodebetter/icodebetter/issues/8). 
The installation go fine.
The server starts successfully.
Browsing localhost:8080 I'm being redirected to the auth0 login page.
I login with my linkedin test user, but after the validation, I receive this error:

{"success":false, "errorType":"framework","error":"ERROR: relation \"iwb.w5_external_db\" does not exist\n Position: 397", "objectType":"DataBase.Exception", "stack":"iwb.exception.IWBException: Custom Query2List: ERROR: current transaction is aborted, commands ignored until end of transaction block\n\tat iwb.dao.rdbms_impl.BaseDAO.executeSQLQuery(BaseDAO.java:249)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadFrameworkCaches(MetadataLoaderDAO.java:1458)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$FastClassBySpringCGLIB$$1e052681.invoke()\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n\tat org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$EnhancerBySpringCGLIB$$65e0375a.reloadFrameworkCaches()\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$FastClassBySpringCGLIB$$1e052681.invoke()\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO$$EnhancerBySpringCGLIB$$c146c1d4.reloadFrameworkCaches()\n\tat iwb.service.FrameworkService.saveCredentials(FrameworkService.java:1956)\n\tat iwb.service.FrameworkService$$FastClassBySpringCGLIB$$f1b24cca.invoke()\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\n\tat org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)\n\tat iwb.service.FrameworkService$$EnhancerBySpringCGLIB$$4c04f60e.saveCredentials()\n\tat iwb.controller.AuthController.handle(AuthController.java:133)\n\tat iwb.controller.AuthController.getCallback(AuthController.java:76)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat iwb.filter.AppFilter.doFilter(AppFilter.java:54)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.hibernate.exception.GenericJDBCException: error executing work\n\tat org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)\n\tat org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:337)\n\tat org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2153)\n\tat org.hibernate.internal.SessionImpl.doReturningWork(SessionImpl.java:2149)\n\tat iwb.dao.rdbms_impl.BaseDAO.executeSQLQuery(BaseDAO.java:210)\n\t... 83 more\nCaused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)\n\tat sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)\n\tat com.sun.proxy.$Proxy80.executeQuery(Unknown Source)\n\tat iwb.dao.rdbms_impl.BaseDAO$1.execute(BaseDAO.java:226)\n\tat iwb.dao.rdbms_impl.BaseDAO$1.execute(BaseDAO.java:210)\n\tat org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55)\n\tat org.hibernate.internal.SessionImpl$4.accept(SessionImpl.java:2146)\n\tat org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:332)\n\t... 86 more\nCaused by: org.postgresql.util.PSQLException: ERROR: relation \"iwb.w5_external_db\" does not exist\n Position: 397\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)\n\tat sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)\n\tat com.sun.proxy.$Proxy80.executeQuery(Unknown Source)\n\tat org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)\n\tat org.hibernate.loader.Loader.getResultSet(Loader.java:2117)\n\tat org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1900)\n\tat org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)\n\tat org.hibernate.loader.Loader.doQuery(Loader.java:919)\n\tat org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)\n\tat org.hibernate.loader.Loader.doList(Loader.java:2617)\n\tat org.hibernate.loader.Loader.doList(Loader.java:2600)\n\tat org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)\n\tat org.hibernate.loader.Loader.list(Loader.java:2424)\n\tat org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)\n\tat org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)\n\tat org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)\n\tat org.hibernate.internal.SessionImpl.list(SessionImpl.java:1326)\n\tat org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)\n\tat iwb.dao.rdbms_impl.BaseDAO.find(BaseDAO.java:63)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadExternalDbsCache(MetadataLoaderDAO.java:933)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadProjectCaches(MetadataLoaderDAO.java:1594)\n\tat iwb.dao.rdbms_impl.MetadataLoaderDAO.reloadFrameworkCaches(MetadataLoaderDAO.java:1455)\n\t... 82 more\n", "sql":"select x.related_project_uuid, string_agg(x.user_id::text,',') from iwb.w5_user_related_project x group by x.related_project_uuid", "icodebetter":[{"errorType":"request","objectType":"Web.Request","error":"/auth/callback"},{"errorType":"sql","error":"Custom Query2List: ERROR: current transaction is aborted, commands ignored until end of transaction block","sql":"select x.related_project_uuid, string_agg(x.user_id::text,',') from iwb.w5_user_related_project x group by x.related_project_uuid","objectType":"Custom.Query.List","objectId":0},{"errorType":"framework","error":"ERROR: relation \"iwb.w5_external_db\" does not exist\n Position: 397","objectType":"DataBase.Exception","objectId":0}]}

In the database "iwb" the table  w5_external_db does not exists. I've imported the backup on github but the table are missing.

Is there a method to synch table with application?
How can I update/upgrade application and DB in case o new release con github?

Thanks,
Fabio.

**What you did**:

**What happened**:

**Problem description**:

**Comment by fabiograz** [comment]
I've manually added w5_external_db find column on the source code https://github.com/icodebetter/icodebetter/blob/master/src/main/java/iwb/domain/db/W5ExternalDb.java but now on DB table w5_mq is miss. There are many difference between db schema installed and the required one. It needs a sync method between application e DB.

**Comment by veliozturk** [comment]
Hi Fabio,
you can auto-update metadata tables (w5_external_db, w5_mq etc..) by starting the project with project=1 parameter

PS: before starting, drop the w5_external_db table

**Comment by hugsyy** [comment]
@fabiograz Hello, keep db container running (assuming you started it using docker-compose) and restart web container with `project=1` parameter:
```
docker container stop web
docker container prune -f
docker run -d -p 8080:8080 --network=icb --name=web icodebetter/graal_image project=1
```

**Comment by fabiograz** [comment]
Ok, it works!

Is this method used to upgrade the framework?

What happens to the applications I developed?
 
Thanks.

**Comment by hugsyy** [comment]
@fabiograz This method is used to update the framework. It will not affect the applications you develop on the platform.

**Comment by fabiograz** [comment]
Ok, thanks.
